name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        rm -rf $(ls -a -I '.' -I '..' -I '.git')
        docker pull ModifiedCommand/convert-minecraft-java-texture-to-bedrock-webapp
        docker run -d --name convert-minecraft-java-texture-to-bedrock-webapp ModifiedCommand/convert-minecraft-java-texture-to-bedrock-webapp
        docker cp convert-minecraft-java-texture-to-bedrock-webapp:/usr/local/apache2/htdocs/ ./
        docker container rm convert-minecraft-java-texture-to-bedrock-webapp -f
        cp -r htdocs/* .
        rm -rf htdocs
      
    - name: Sigin to git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
      
    - name: Commit
      run: |
        git add .
        git commit -m "GitHub Actions"
      
    - name: Push commit
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: "gh-pages"
